name = "clean-new-tab-oauth"
main = "src/index.js"
compatibility_date = "2026-08-01"
workers_dev = true

[observability]
enabled = true

[vars]
GOOGLE_REDIRECT_URI = "http://127.0.0.1/mozoauth2/e697e40c882940b0642dddbae923c59b0596f579"
